{% set name = "gender-guesser" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gender-guesser-{{ version }}.tar.gz
  sha256: 1591c14592805ca7da06a46d5f7202511f7cb87547049a68dfccbeedb879f31b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - tox
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - gender_guesser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lead-ratings/gender-guesser
  summary: Get the gender from first name.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
