schema_version: 1

context:
  name: gender-guesser
  version: 0.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gender-guesser-${{ version }}.tar.gz
  sha256: 1591c14592805ca7da06a46d5f7202511f7cb87547049a68dfccbeedb879f31b

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - tox
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - gender_guesser
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: Get the gender from first name.
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/lead-ratings/gender-guesser

extra:
  recipe-maintainers:
    - rxm7706
